spring.application.name=bank-management-system-v4
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/demo2
spring.datasource.username=postgres
spring.datasource.password=Subhashini@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.sql.init.mode=always
